### ISSUE TITLE
Paranoid fonts don't work in Chrome

### ISSUE THREAD

**Issue by miketaylr** [operasoftware/shinydemos#171]
Vadim pointed out it's .ttf only... but I thought Chrome supported .ttf? Problem with the font file?

``` css
@font-face {
   font-family: "Adore64";
   src: url(../Adore64.ttf)
}
```
