### ISSUE TITLE
Beach demo also needs style isolation

### ISSUE THREAD

**Issue by pepelsbey** [operasoftware/shinydemos#188]
…as it affects (at least) panel switcher.

``` css
button {
    border-radius: 3px
    }
```
